services:

  mysql:
    image: mysql:8.0-debian
    container_name: mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nodeapp
    volumes:
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/schema.sql
      - ./.docker/mysql:/var/lib/mysql

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    entrypoint: wait-for mysql:3306 -t 60 -- nginx -g 'daemon off;'
    ports:
      - 8080:80
    depends_on:
      - node

  node:
    build:
      context: ./node
    container_name: node
    entrypoint: wait-for mysql:3306 -t 60 -- node index.js
    tty: true
    depends_on:
      - mysql
